(()=>{'use strict';
const $=id=>document.getElementById(id),modes={gridshot:{name:'GRIDSHOT',icon:'⊞',desc:'Three targets. Rapid switching and fast resets.',count:3,base:35},sixshot:{name:'SIXSHOT',icon:'⠿',desc:'Six tiny targets. Train pinpoint precision.',count:6,base:17},reflex:{name:'REFLEX',icon:'⚡',desc:'Wait for the target, then react instantly.',count:1,base:34},tracking:{name:'TRACKING',icon:'◎',desc:'Keep your cursor on a moving target.',count:1,base:37},microshot:{name:'MICROSHOT',icon:'⌖',desc:'Tiny targets clustered around the centre.',count:1,base:18},flickshot:{name:'FLICKSHOT',icon:'✦',desc:'Unpredictable targets. Explosive flicks.',count:1,base:31}};
const defaults={duration:'60',difficulty:'normal',size:'normal',speed:'normal',spawn:'normal',crosshair:'cross',crosshairColor:'#ffffff',crosshairSize:'16',sensitivity:'100',sound:true,music:false,effects:true,pointerlock:false};
let saved;try{saved=JSON.parse(localStorage.getItem('precision-v1'))||{}}catch{saved={}}let settings={...defaults,...(saved.settings||{})},history=Array.isArray(saved.history)?saved.history:[],mode='gridshot';
const save=()=>{try{localStorage.setItem('precision-v1',JSON.stringify({settings,history:history.slice(-500)}))}catch{toast('Browser storage unavailable')}};let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),rand=(a,b)=>a+Math.random()*(b-a),round=n=>Math.round(n),format=n=>Number.isFinite(n)?n.toFixed(1):'—';
$('modes').innerHTML=Object.entries(modes).map(([id,m])=>'<button class="mode-card '+(id===mode?'selected':'')+'" data-mode="'+id+'"><div class="mode-icon">'+m.icon+'</div><h3>'+m.name+'</h3><p>'+m.desc+'</p></button>').join('');
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b))});
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));$('title').textContent={play:'Train with purpose.',history:'Your performance.',settings:'Dial it in.'}[b.dataset.page];$('subtitle').textContent={play:'Select a drill. Sharpen your aim.',history:'Track progress and chase your personal best.',settings:'Make every drill feel right.'}[b.dataset.page];if(b.dataset.page==='history')renderHistory()});
const ids=['duration','difficulty','size','speed','spawn','crosshair','crosshair-color','crosshair-size','sensitivity','sound','music','effects','pointerlock'],keys=['duration','difficulty','size','speed','spawn','crosshair','crosshairColor','crosshairSize','sensitivity','sound','music','effects','pointerlock'];ids.forEach((id,i)=>{const e=$(id),key=keys[i];if(e.type==='checkbox')e.checked=!!settings[key];else e.value=settings[key];e.addEventListener('input',()=>{settings[key]=e.type==='checkbox'?e.checked:e.value;save()})});
function renderHistory(){$('sessions').textContent=history.length;const acc=history.length?Math.max(...history.map(h=>h.accuracy)):null;$('best-accuracy').textContent=acc===null?'—':format(acc)+'%';const bests=Object.entries(modes).map(([id,m])=>{const h=history.filter(x=>x.mode===id).sort((a,b)=>b.score-a.score)[0];return '<div class="history-row"><b>'+m.name+'</b><span>'+(h?h.score.toLocaleString():'—')+'</span><span>'+(h?format(h.accuracy)+'%':'—')+'</span><span>'+(h?h.duration+'s':'—')+'</span><span>'+(h?new Date(h.at).toLocaleDateString('en-GB'):'—')+'</span></div>'});$('bests').innerHTML='<div class="history-row"><small>MODE</small><small>BEST SCORE</small><small>ACCURACY</small><small>DURATION</small><small>DATE</small></div>'+bests.join('');$('history-list').innerHTML=history.length?'<div class="history-row"><small>MODE</small><small>SCORE</small><small>ACCURACY</small><small>AVG REACTION</small><small>DATE</small></div>'+history.slice().reverse().map(h=>'<div class="history-row"><b>'+modes[h.mode].name+'</b><span>'+h.score.toLocaleString()+'</span><span>'+format(h.accuracy)+'%</span><span>'+(h.avgReaction===null?'—':round(h.avgReaction)+'ms')+'</span><span>'+new Date(h.at).toLocaleString('en-GB')+'</span></div>').join(''):'<div class="empty">No sessions yet. Your training history will appear here.</div>';const canvas=$('trend'),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.strokeStyle='#28415a';c.lineWidth=1;for(let i=1;i<5;i++){c.beginPath();c.moveTo(35,h*i/5);c.lineTo(w-15,h*i/5);c.stroke()}const data=history.slice(-20);if(!data.length)return;const max=Math.max(1,...data.map(x=>x.score)),step=(w-65)/Math.max(1,data.length-1);c.beginPath();data.forEach((x,i)=>{const px=35+i*step,py=h-28-(x.score/max)*(h-58);if(!i)c.moveTo(px,py);else c.lineTo(px,py)});c.strokeStyle='#37e5e9';c.lineWidth=3;c.stroke();data.forEach((x,i)=>{c.beginPath();c.arc(35+i*step,h-28-x.score/max*(h-58),4,0,Math.PI*2);c.fillStyle='#58a4ff';c.fill()})}
$('clear-history').onclick=()=>{if(confirm('Clear all local performance history?')){history=[];save();renderHistory()}};renderHistory();
const arena=$('arena'),canvas=$('arena-canvas'),ctx=canvas.getContext('2d'),cross=$('cross');let W=0,H=0,dpr=1,game=null,raf=0,prev=0,pointer={x:0,y:0},audio=null,ambient=null;
function resize(){const rect=arena.getBoundingClientRect();W=Math.max(1,rect.width);H=Math.max(1,rect.height);dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=round(W*dpr);canvas.height=round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(game){for(const t of game.targets){t.x=clamp(t.x,t.r,W-t.r);t.y=clamp(t.y,t.r,H-t.r)}pointer.x=clamp(pointer.x,0,W);pointer.y=clamp(pointer.y,0,H)}}
window.addEventListener('resize',resize);
function settingsValue(key){return ({easy:1.25,normal:1,hard:.75,small:.72,large:1.35,slow:.65,fast:1.5})[settings[key]]||1}
function radius(){const m=modes[mode];return clamp(m.base*settingsValue('size')*({easy:1.18,normal:1,hard:.82}[settings.difficulty]||1),8,90)}
function newTarget(existing=[]){const r=Math.min(radius(),Math.max(8,Math.min(W,H)/5)),pad=r+8;let x,y;for(let k=0;k<35;k++){if(mode==='microshot'){x=W/2+rand(-Math.min(W*.23,180),Math.min(W*.23,180));y=H/2+rand(-Math.min(H*.23,135),Math.min(H*.23,135))}else{x=rand(pad,Math.max(pad,W-pad));y=rand(pad,Math.max(pad,H-pad))}x=clamp(x,pad,Math.max(pad,W-pad));y=clamp(y,pad,Math.max(pad,H-pad));if(existing.every(t=>Math.hypot(t.x-x,t.y-y)>r+t.r+8))break}const angle=rand(0,Math.PI*2),speed=({slow:70,normal:125,fast:200}[settings.speed]||125)*({easy:.7,normal:1,hard:1.35}[settings.difficulty]||1);return{x,y,r,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,born:performance.now(),id:crypto.randomUUID()}}
function spawnTargets(now){if(!game)return;game.targets=[];for(let i=0;i<modes[mode].count;i++)game.targets.push(newTarget(game.targets));if(mode==='reflex'){game.targets=[];game.nextSpawn=now+rand(500,1600)/settingsValue('spawn')}}
function replaceTarget(index,now){game.targets.splice(index,1);if(mode==='reflex'){game.nextSpawn=now+rand(350,1500)/settingsValue('spawn')}else{const target=newTarget(game.targets);target.born=now;game.targets.push(target)}}
function initAudio(){if(!settings.sound&&!settings.music)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch{}}
function beep(freq=650,vol=.055,len=.075){if(!audio||!settings.sound)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+len);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+len)}
function ambientStart(){ambientStop();if(!settings.music||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=82;gain.gain.value=.008;osc.connect(gain).connect(audio.destination);osc.start();ambient={osc,gain}}
function ambientStop(){if(ambient){try{ambient.osc.stop()}catch{}ambient=null}}
function crosshair(){const size=Number(settings.crosshairSize),color=settings.crosshairColor;cross.style.left=pointer.x+'px';cross.style.top=pointer.y+'px';cross.style.width=size*2+'px';cross.style.height=size*2+'px';cross.style.background='none';cross.style.border='none';cross.style.borderRadius='0';if(settings.crosshair==='dot'){cross.style.width='6px';cross.style.height='6px';cross.style.borderRadius='50%';cross.style.background=color}else if(settings.crosshair==='circle'){cross.style.border='2px solid '+color;cross.style.borderRadius='50%'}else{cross.style.background='linear-gradient('+color+','+color+') center / 2px 100% no-repeat,linear-gradient('+color+','+color+') center / 100% 2px no-repeat'}}
function start(){stop(false);mode=mode in modes?mode:'gridshot';$('game').classList.remove('hidden');$('results').classList.add('hidden');$('pause-overlay').classList.add('hidden');resize();pointer={x:W/2,y:H/2};const now=performance.now();game={phase:'countdown',countdownEnd:now+3000,started:0,elapsed:0,duration:Number(settings.duration)*1000,targets:[],hits:0,misses:0,clicks:0,score:0,reactions:[],trackingMs:0,trackingOn:0,effects:[],nextSpawn:0,pausedAt:0,lastHud:0};$('mode-label').textContent=modes[mode].name;$('countdown').classList.remove('hidden');initAudio();ambientStart();if(settings.pointerlock&&arena.requestPointerLock)arena.requestPointerLock().catch(()=>toast('Pointer lock unavailable. Native cursor works too.'));prev=now;raf=requestAnimationFrame(frame)}
function stop(showMenu=true){cancelAnimationFrame(raf);ambientStop();if(document.pointerLockElement===arena)document.exitPointerLock();game=null;$('countdown').classList.add('hidden');$('pause-overlay').classList.add('hidden');$('results').classList.add('hidden');if(showMenu){$('game').classList.add('hidden');renderHistory()}}
function pause(){if(!game||game.phase==='finished'||game.phase==='countdown')return;if(game.phase==='paused'){const delta=performance.now()-game.pausedAt;game.started+=delta;for(const t of game.targets)t.born+=delta;if(game.nextSpawn)game.nextSpawn+=delta;game.phase='running';$('pause-overlay').classList.add('hidden');prev=performance.now();if(settings.pointerlock&&document.pointerLockElement!==arena)arena.requestPointerLock?.().catch(()=>{});ambientStart()}else{game.phase='paused';game.pausedAt=performance.now();$('pause-overlay').classList.remove('hidden');ambientStop();if(document.pointerLockElement===arena)document.exitPointerLock()}}
function finish(){if(!game||game.phase==='finished')return;game.phase='finished';ambientStop();if(document.pointerLockElement===arena)document.exitPointerLock();const accuracy=mode==='tracking'?(game.elapsed?game.trackingOn/game.elapsed*100:0):(game.clicks?game.hits/game.clicks*100:0),avg=game.reactions.length?game.reactions.reduce((a,b)=>a+b,0)/game.reactions.length:null,entry={mode,score:round(game.score),accuracy:Math.min(100,accuracy),hits:game.hits,misses:game.misses,cps:game.clicks/(game.duration/1000),avgReaction:avg,duration:Number(settings.duration),at:new Date().toISOString()};const prior=Math.max(0,...history.filter(x=>x.mode===mode&&x.duration===entry.duration).map(x=>x.score));history.push(entry);save();$('result-title').textContent=entry.score>prior?'NEW PERSONAL BEST!':'SESSION COMPLETE';$('result-grid').innerHTML=[['SCORE',entry.score.toLocaleString()],['ACCURACY',format(entry.accuracy)+'%'],['HITS',entry.hits],['MISSES',entry.misses],['CPS',format(entry.cps)],['AVG REACTION',avg===null?'—':round(avg)+' ms']].map(([k,v])=>'<div class="result-stat"><small>'+k+'</small><strong>'+v+'</strong></div>').join('');$('result-best').textContent=entry.score>prior?'★ NEW '+entry.duration+'s '+modes[mode].name+' RECORD':'Previous best: '+prior.toLocaleString();$('results').classList.remove('hidden');$('countdown').classList.add('hidden')}
function draw(){ctx.clearRect(0,0,W,H);ctx.strokeStyle='#253449';ctx.lineWidth=1;const step=55;for(let x=step;x<W;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=step;y<H;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}if(!game)return;for(const t of game.targets){ctx.beginPath();ctx.arc(t.x,t.y,t.r+7,0,Math.PI*2);ctx.fillStyle='#30d9eb15';ctx.fill();ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fillStyle='#29d7e8';ctx.shadowBlur=22;ctx.shadowColor='#21c9ff';ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(t.x,t.y,t.r*.56,0,Math.PI*2);ctx.fillStyle='#e9fcff';ctx.fill();ctx.beginPath();ctx.arc(t.x,t.y,t.r*.22,0,Math.PI*2);ctx.fillStyle='#0c5473';ctx.fill()}for(const fx of game.effects){ctx.beginPath();ctx.arc(fx.x,fx.y,fx.r,0,Math.PI*2);ctx.strokeStyle='rgba(58,232,255,'+fx.alpha+')';ctx.lineWidth=3;ctx.stroke()}crosshair()}
function updateHud(now){if(now-game.lastHud<70)return;game.lastHud=now;$('hud-time').textContent=(Math.max(0,game.duration-game.elapsed)/1000).toFixed(1);$('hud-score').textContent=round(game.score).toLocaleString();const accuracy=mode==='tracking'?(game.elapsed?game.trackingOn/game.elapsed*100:0):(game.clicks?game.hits/game.clicks*100:100);$('hud-accuracy').textContent=format(accuracy)+'%';$('hud-hits').textContent=game.hits+' / '+game.misses;$('hud-cps').textContent=format(game.clicks/Math.max(.1,game.elapsed/1000));$('hud-reaction').textContent=game.reactions.length?round(game.reactions.reduce((a,b)=>a+b,0)/game.reactions.length)+'ms':'—'}
function frame(now){if(!game)return;const dt=clamp(now-prev,0,50);prev=now;if(game.phase==='countdown'){const remain=game.countdownEnd-now;$('countdown').textContent=remain>0?Math.ceil(remain/1000):'GO';if(remain<=-350){game.phase='running';game.started=now;game.elapsed=0;spawnTargets(now);$('countdown').classList.add('hidden')}}else if(game.phase==='running'){game.elapsed=Math.min(game.duration,now-game.started);if(mode==='reflex'&&game.targets.length===0&&now>=game.nextSpawn)game.targets.push(newTarget());if(mode==='tracking'){const t=game.targets[0];if(t){t.x+=t.vx*dt/1000;t.y+=t.vy*dt/1000;if(t.x<t.r||t.x>W-t.r){t.vx*=-1;t.x=clamp(t.x,t.r,W-t.r)}if(t.y<t.r||t.y>H-t.r){t.vy*=-1;t.y=clamp(t.y,t.r,H-t.r)}const on=Math.hypot(pointer.x-t.x,pointer.y-t.y)<=t.r;if(on){game.trackingOn+=dt;game.score+=dt*.11;game.hits=Math.floor(game.trackingOn/100);beepTracking(now)}else game.misses=Math.floor((game.elapsed-game.trackingOn)/100)}}game.effects=game.effects.filter(fx=>{fx.r+=dt*.11;fx.alpha-=dt*.003;return fx.alpha>0});updateHud(now);if(game.elapsed>=game.duration)finish()}draw();raf=requestAnimationFrame(frame)}
let lastTrackSound=0;function beepTracking(now){if(now-lastTrackSound>420){lastTrackSound=now;beep(420,.008,.03)}}
function aimPoint(e){const rect=arena.getBoundingClientRect();if(document.pointerLockElement===arena){const factor=Number(settings.sensitivity)/100;pointer.x=clamp(pointer.x+e.movementX*factor,0,W);pointer.y=clamp(pointer.y+e.movementY*factor,0,H)}else{pointer.x=clamp(e.clientX-rect.left,0,W);pointer.y=clamp(e.clientY-rect.top,0,H)}}arena.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.pointerType==='pen')aimPoint(e)},{passive:true});
arena.addEventListener('pointerdown',e=>{if(e.button!==0||!game||game.phase!=='running')return;e.preventDefault();if(document.pointerLockElement!==arena)aimPoint(e);if(mode==='tracking'){game.clicks++;return}game.clicks++;const now=performance.now(),idx=game.targets.findIndex(t=>Math.hypot(t.x-pointer.x,t.y-pointer.y)<=t.r);if(idx<0){game.misses++;beep(175,.03,.04)}else{const t=game.targets[idx];game.hits++;game.score+=mode==='sixshot'?150:mode==='microshot'?130:mode==='reflex'?Math.max(30,round(400-(now-t.born)*.3)):100;game.reactions.push(now-t.born);if(settings.effects)game.effects.push({x:t.x,y:t.y,r:t.r,alpha:1});beep(850);replaceTarget(idx,now)}updateHud(now)});
document.addEventListener('keydown',e=>{if(!game)return;if(e.key==='Escape'){if(document.pointerLockElement===arena)return;stop();return}if(e.key.toLowerCase()==='p'){e.preventDefault();pause()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.phase==='running')pause()});
$('start').onclick=start;$('pause').onclick=pause;$('resume').onclick=pause;$('quit').onclick=()=>stop();$('restart-pause').onclick=start;$('again').onclick=start;$('back').onclick=()=>stop();$('fullscreen').onclick=()=>{if(!document.fullscreenElement)$('game').requestFullscreen?.().catch(()=>toast('Fullscreen unavailable'));else document.exitFullscreen?.()};
})();