(()=>{'use strict';
const KEY='vault-finance-v1',today=()=>new Date().toLocaleDateString('en-CA'),monthNow=()=>today().slice(0,7);
const defaults=[['Salary','income','💼','#39d6a0'],['Other income','income','✨','#80c7f5'],['Food','expense','🍽️','#ffb86b'],['Transport','expense','🚗','#72a7ff'],['Shopping','expense','🛍️','#d4a0ff'],['Bills','expense','🏠','#f77f88'],['Entertainment','expense','🎮','#e2c36b'],['Other','expense','📦','#93a9a4']].map(([name,type,icon,color])=>({id:crypto.randomUUID(),name,type,icon,color}));
const fresh=()=>({transactions:[],goals:[],budgets:[],categories:defaults,recurring:[],theme:'dark',demo:false});
let db;try{db=JSON.parse(localStorage.getItem(KEY))||fresh();if(!Array.isArray(db.transactions)||!Array.isArray(db.goals))throw Error('Invalid save');db={...fresh(),...db}}catch{db=fresh()}
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID(),sum=(arr,fn=x=>x)=>arr.reduce((s,x)=>s+fn(x),0);
function pennies(v){if(!/^\d+(\.\d{1,2})?$/.test(String(v).trim()))return null;const [p,c='']=String(v).split('.');const n=Number(p)*100+Number(c.padEnd(2,'0'));return Number.isSafeInteger(n)&&n>0?n:null}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db))}catch{toast('Browser storage unavailable. Export a backup.')}};
let toastTimer;function toast(s){const t=$('toast');t.textContent=s;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',3500)}
const category=id=>db.categories.find(c=>c.id===id)||{name:'Uncategorised',icon:'◈',color:'#81908c',type:'expense'};
const fmtDate=s=>new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const transactionHTML=t=>{const c=category(t.categoryId);return '<div class="tx"><div class="tx-icon">'+esc(c.icon)+'</div><div class="tx-info"><strong>'+esc(t.description)+'</strong><small>'+esc(c.name)+' · '+fmtDate(t.date)+(t.recurringId?' · Recurring':'')+'</small></div><span class="amount '+(t.type==='income'?'positive':'negative')+'">'+(t.type==='income'?'+':'−')+money(t.amount)+'</span><div class="tx-actions"><button data-edit="'+esc(t.id)+'" aria-label="Edit transaction">✎</button><button data-delete="'+esc(t.id)+'" aria-label="Delete transaction">✕</button></div></div>'};
const txSorted=()=>[...db.transactions].sort((a,b)=>b.date.localeCompare(a.date)||b.created.localeCompare(a.created));
function page(name){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===name));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===name));$('heading').textContent=({dashboard:'Dashboard',transactions:'Transactions',goals:'Savings goals',budgets:'Budgets',settings:'Settings'})[name];render()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto));
function render(){const income=sum(db.transactions.filter(t=>t.type==='income'),t=>t.amount),expenses=sum(db.transactions.filter(t=>t.type==='expense'),t=>t.amount),allocated=sum(db.goals,g=>g.saved);$('balance').textContent=money(income-expenses-allocated);$('income').textContent=money(income);$('expenses').textContent=money(expenses);
const m=monthNow(),mi=sum(db.transactions.filter(t=>t.type==='income'&&t.date.startsWith(m)),t=>t.amount),me=sum(db.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(m)),t=>t.amount);$('monthly-savings').textContent=money(mi-me);$('savings-rate').textContent='Savings rate: '+(mi?Math.round((mi-me)/mi*100):0)+'%';$('demo-pill').classList.toggle('hidden',!db.demo);
const recent=txSorted().slice(0,5);$('recent').innerHTML=recent.length?recent.map(transactionHTML).join(''):'<div class="empty">No transactions yet. Add your first one!</div>';
const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-(5-i));return d.toISOString().slice(0,7)}),totals=months.map(m=>({m,inc:sum(db.transactions.filter(t=>t.type==='income'&&t.date.startsWith(m)),t=>t.amount),exp:sum(db.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(m)),t=>t.amount)})),max=Math.max(1,...totals.flatMap(x=>[x.inc,x.exp]));$('bars').innerHTML=totals.map(x=>'<div class="bar-group" title="'+esc(x.m)+' income '+money(x.inc)+', expenses '+money(x.exp)+'"><div class="bar income" style="height:'+Math.max(1,x.inc/max*95)+'%"></div><div class="bar expense" style="height:'+Math.max(1,x.exp/max*95)+'%"></div><label>'+esc(new Date(x.m+'-01T12:00:00').toLocaleDateString('en-GB',{month:'short'}))+'</label></div>').join('');
const byCat=db.categories.filter(c=>c.type==='expense').map(c=>({...c,value:sum(db.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(m)&&t.categoryId===c.id),t=>t.amount)})).filter(c=>c.value>0),total=sum(byCat,c=>c.value);let cursor=0;const gradients=byCat.map(c=>{const start=cursor;cursor+=c.value/total*100;return c.color+' '+start+'% '+cursor+'%'});$('donut').style.background=gradients.length?'conic-gradient('+gradients.join(',')+')':'conic-gradient(#334742 0 100%)';$('donut-total').textContent=money(total);$('donut-legend').innerHTML=byCat.length?byCat.map(c=>'<div class="legend-item"><span><i class="dot" style="background:'+c.color+'"></i> '+esc(c.name)+'</span><strong>'+money(c.value)+'</strong></div>').join(''):'<p class="muted">No expenses this month</p>';
renderTransactions();renderGoals();renderBudgets();renderSettings()}
function renderTransactions(){const search=$('search').value.toLowerCase(),month=$('month').value,type=$('filter-type').value,sort=$('sort').value;let tx=db.transactions.filter(t=>(!month||t.date.startsWith(month))&&(type==='all'||t.type===type)&&(t.description.toLowerCase().includes(search)||category(t.categoryId).name.toLowerCase().includes(search)));tx.sort((a,b)=>sort==='oldest'?a.date.localeCompare(b.date):sort==='high'?b.amount-a.amount:sort==='low'?a.amount-b.amount:b.date.localeCompare(a.date));$('transaction-list').innerHTML=tx.length?tx.map(transactionHTML).join(''):'<div class="empty">No matching transactions.</div>';const recurring=db.recurring;$('recurring-list').innerHTML=recurring.length?recurring.map(r=>'<div class="tx"><div class="tx-info"><strong>'+esc(r.description)+'</strong><small>'+esc(r.frequency)+' · next '+fmtDate(r.nextDate)+'</small></div><span>'+money(r.amount)+'</span><button class="secondary" data-stop="'+esc(r.id)+'">Stop</button></div>').join(''):'<div class="empty">No recurring transactions configured.</div>'}
['search','month','filter-type','sort'].forEach(id=>$(id).addEventListener('input',renderTransactions));$('clear-filters').onclick=()=>{$('search').value='';$('month').value='';$('filter-type').value='all';$('sort').value='newest';renderTransactions()};
const goalCard=g=>'<div class="goal"><h3>'+esc(g.name)+'</h3><strong>'+money(g.saved)+'</strong><small>of '+money(g.target)+' · Due '+(g.deadline?fmtDate(g.deadline):'anytime')+'</small><div class="progress"><div style="width:'+Math.min(100,g.saved/g.target*100)+'%"></div></div><small>'+Math.round(g.saved/g.target*100)+'% saved</small><div class="goal-actions"><button class="secondary" data-contribute="'+esc(g.id)+'">+ Contribute</button><button class="secondary" data-withdraw="'+esc(g.id)+'">Withdraw</button><button class="secondary" data-edit-goal="'+esc(g.id)+'">Edit</button><button class="danger" data-delete-goal="'+esc(g.id)+'">Delete</button></div></div>';
function renderGoals(){$('goals-list').innerHTML=db.goals.length?db.goals.map(goalCard).join(''):'<div class="empty">No savings goals yet. Create one to get started.</div>';$('goal-preview').innerHTML=db.goals.length?db.goals.slice(0,2).map(g=>'<div class="budget-row"><strong>'+esc(g.name)+'</strong><small class="muted"> · '+money(g.saved)+' / '+money(g.target)+'</small><div class="progress"><div style="width:'+Math.min(100,g.saved/g.target*100)+'%"></div></div></div>').join(''):'<div class="empty">No goals yet.</div>'}
function renderBudgets(){const m=monthNow();$('budgets-list').innerHTML=db.budgets.length?db.budgets.map(b=>{const c=category(b.categoryId),spent=sum(db.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(m)&&t.categoryId===b.categoryId),t=>t.amount),pct=spent/b.limit*100;return '<div class="budget-row"><div class="budget-head"><strong>'+esc(c.icon)+' '+esc(c.name)+'</strong><span class="'+(pct>100?'warning':'')+'">'+money(spent)+' / '+money(b.limit)+(pct>100?' · OVER BUDGET':'')+'</span><button class="secondary" data-edit-budget="'+esc(b.categoryId)+'">Edit</button><button class="danger" data-delete-budget="'+esc(b.categoryId)+'">Remove</button></div><div class="progress"><div style="width:'+Math.min(100,pct)+'%;background:'+(pct>100?'var(--red)':'var(--green)')+'"></div></div></div>'}).join(''):'<div class="empty">No budgets yet. Set a monthly spending limit.</div>'}
function renderSettings(){$('categories-list').innerHTML=db.categories.map(c=>'<span class="category-tag">'+esc(c.icon)+' '+esc(c.name)+' <small class="muted">('+esc(c.type)+')</small></span>').join('')}
const modal=$('modal');let onSave=null;function openForm(title,fields,submit){$('modal-title').textContent=title;$('fields').innerHTML=fields;onSave=submit;modal.showModal();setTimeout(()=>modal.querySelector('input,select')?.focus(),50)}$('close').onclick=$('cancel').onclick=()=>modal.close();$('entry-form').onsubmit=e=>{e.preventDefault();try{if(onSave()!==false){save();modal.close();render()}}catch(err){toast(err.message||'Could not save')}};
const field=(label,id,type='text',value='',extra='')=>'<div class="field"><label for="'+id+'">'+esc(label)+'</label><input id="'+id+'" type="'+type+'" value="'+esc(value)+'" '+extra+' required></div>';
const selectField=(label,id,options,selected)=>'<div class="field"><label for="'+id+'">'+esc(label)+'</label><select id="'+id+'">'+options.map(o=>'<option value="'+esc(o[0])+'" '+(o[0]===selected?'selected':'')+'>'+esc(o[1])+'</option>').join('')+'</select></div>';
function txForm(existing){const t=existing||{type:'expense',date:today(),amount:0,description:'',categoryId:db.categories.find(c=>c.type==='expense')?.id},types=[['expense','Expense'],['income','Income']];openForm(existing?'Edit transaction':'New transaction',selectField('Type','f-type',types,t.type)+field('Description','f-description','text',t.description,'maxlength="100"')+field('Amount (£)','f-amount','text',t.amount?(t.amount/100).toFixed(2):'','inputmode="decimal" placeholder="0.00"')+field('Date','f-date','date',t.date)+selectField('Category','f-category',db.categories.filter(c=>c.type===t.type).map(c=>[c.id,c.icon+' '+c.name]),t.categoryId)+(existing?'':'<div class="field"><label><input type="checkbox" id="f-recurring"> Repeat automatically</label></div><div id="repeat-fields" class="hidden">'+selectField('Frequency','f-frequency',[['weekly','Weekly'],['monthly','Monthly']],'monthly')+'</div>'),()=>{const type=$('f-type').value,amount=pennies($('f-amount').value),description=$('f-description').value.trim(),date=$('f-date').value,categoryId=$('f-category').value;if(!amount||!description||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!db.categories.some(c=>c.id===categoryId&&c.type===type)){toast('Check the transaction details and positive amount.');return false}const item={id:existing?.id||uid(),type,amount,description,date,categoryId,created:existing?.created||new Date().toISOString(),recurringId:existing?.recurringId||null,demo:existing?.demo||false};if(existing)db.transactions=db.transactions.map(x=>x.id===existing.id?item:x);else db.transactions.push(item);if(!existing&&$('f-recurring').checked){const frequency=$('f-frequency').value;db.recurring.push({id:uid(),type,amount,description,categoryId,frequency,nextDate:advance(date,frequency),demo:false})}toast('Transaction saved')});$('f-type').onchange=()=>{const type=$('f-type').value;$('f-category').innerHTML=db.categories.filter(c=>c.type===type).map(c=>'<option value="'+esc(c.id)+'">'+esc(c.icon+' '+c.name)+'</option>').join('')};if(!existing)$('f-recurring').onchange=()=>{$('repeat-fields').classList.toggle('hidden',!$('f-recurring').checked)}}
$('quick-add').onclick=()=>txForm();document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){txForm(db.transactions.find(t=>t.id===b.dataset.edit))}if(b.dataset.delete&&confirm('Delete this transaction?')){db.transactions=db.transactions.filter(t=>t.id!==b.dataset.delete);save();render()}if(b.dataset.stop&&confirm('Stop future recurring transactions?')){db.recurring=db.recurring.filter(r=>r.id!==b.dataset.stop);save();render()}if(b.dataset.contribute||b.dataset.withdraw){const g=db.goals.find(x=>x.id===(b.dataset.contribute||b.dataset.withdraw));const deposit=!!b.dataset.contribute;openForm(deposit?'Contribute to '+g.name:'Withdraw from '+g.name,field('Amount (£)','f-goal-amount','text','','inputmode="decimal"'),()=>{const n=pennies($('f-goal-amount').value);if(!n||(!deposit&&n>g.saved)){toast('Enter a valid amount within the goal balance.');return false}const available=sum(db.transactions.filter(t=>t.type==='income'),t=>t.amount)-sum(db.transactions.filter(t=>t.type==='expense'),t=>t.amount)-sum(db.goals,x=>x.saved);if(deposit&&n>available){toast('Not enough available balance.');return false}g.saved+=deposit?n:-n;toast('Goal updated')})}if(b.dataset.editGoal)goalForm(db.goals.find(g=>g.id===b.dataset.editGoal));if(b.dataset.deleteGoal&&confirm('Delete this goal? Saved funds will return to available balance.')){db.goals=db.goals.filter(g=>g.id!==b.dataset.deleteGoal);save();render()}if(b.dataset.editBudget)budgetForm(db.budgets.find(x=>x.categoryId===b.dataset.editBudget));if(b.dataset.deleteBudget&&confirm('Remove this budget?')){db.budgets=db.budgets.filter(x=>x.categoryId!==b.dataset.deleteBudget);save();render()}});
function goalForm(g){openForm(g?'Edit savings goal':'New savings goal',field('Goal name','f-goal-name','text',g?.name||'','maxlength="60"')+field('Target (£)','f-target','text',g?(g.target/100).toFixed(2):'','inputmode="decimal"')+'<div class="field"><label for="f-deadline">Deadline (optional)</label><input type="date" id="f-deadline" value="'+esc(g?.deadline||'')+'"></div>',()=>{const name=$('f-goal-name').value.trim(),target=pennies($('f-target').value);if(!name||!target){toast('Enter a name and positive target.');return false}if(g){Object.assign(g,{name,target,deadline:$('f-deadline').value})}else db.goals.push({id:uid(),name,target,saved:0,deadline:$('f-deadline').value,demo:false});toast('Goal saved')})}
$('new-goal').onclick=()=>goalForm();
function budgetForm(b){const options=db.categories.filter(c=>c.type==='expense').map(c=>[c.id,c.name]);openForm(b?'Edit budget':'Set monthly budget',selectField('Expense category','f-budget-cat',options,b?.categoryId||options[0]?.[0])+field('Monthly limit (£)','f-budget-limit','text',b?(b.limit/100).toFixed(2):'','inputmode="decimal"'),()=>{const categoryId=$('f-budget-cat').value,limit=pennies($('f-budget-limit').value);if(!limit||!options.some(o=>o[0]===categoryId)){toast('Choose a category and valid limit.');return false}if(db.budgets.some(x=>x.categoryId===categoryId&&x!==b)){toast('That category already has a budget.');return false}if(b)Object.assign(b,{categoryId,limit});else db.budgets.push({categoryId,limit});toast('Budget saved')})}
$('new-budget').onclick=()=>budgetForm();
$('category-form').onsubmit=e=>{e.preventDefault();const name=$('category-name').value.trim(),type=$('category-kind').value,icon=$('category-icon').value.trim()||'✦',color=$('category-color').value;if(!name||db.categories.some(c=>c.type===type&&c.name.toLowerCase()===name.toLowerCase())){toast('Enter a unique category name.');return}db.categories.push({id:uid(),name,type,icon,color});$('category-name').value='';save();render();toast('Category added')};
function advance(date,frequency){const [y,m,d]=date.split('-').map(Number);if(frequency==='weekly'){const x=new Date(Date.UTC(y,m-1,d+7));return x.toISOString().slice(0,10)}const nextM=m===12?1:m+1,nextY=m===12?y+1:y,last=new Date(Date.UTC(nextY,nextM,0)).getUTCDate();return nextY+'-'+String(nextM).padStart(2,'0')+'-'+String(Math.min(d,last)).padStart(2,'0')}
function applyRecurring(){let changed=false;for(const r of db.recurring){let count=0;while(r.nextDate<=today()&&count++<120){const key=r.id+'|'+r.nextDate;if(!db.transactions.some(t=>t.recurringKey===key)){db.transactions.push({id:uid(),type:r.type,amount:r.amount,description:r.description,categoryId:r.categoryId,date:r.nextDate,created:new Date().toISOString(),recurringId:r.id,recurringKey:key,demo:r.demo||false});changed=true}r.nextDate=advance(r.nextDate,r.frequency);changed=true}}if(changed)save()}
$('theme').onclick=()=>{db.theme=db.theme==='dark'?'light':'dark';applyTheme();save()};function applyTheme(){document.body.classList.toggle('light',db.theme==='light');$('theme').textContent=db.theme==='dark'?'☾ Dark mode':'☀ Light mode'}applyTheme();
function csvCell(v){const s=String(v??'');return '"'+( /^[=+@\-\t\r]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"'}
function exportCSV(){const rows=[['date','type','description','category','amount_gbp'],...txSorted().map(t=>[t.date,t.type,t.description,category(t.categoryId).name,(t.amount/100).toFixed(2)])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vault-transactions-'+today()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}$('export').onclick=exportCSV;
function parseCSV(s){const result=[],rows=[],out=[];let quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'&&s[i+1]==='"'){out.push('"');i++}else if(c==='"')quoted=false;else out.push(c)}else if(c==='"')quoted=true;else if(c===','){rows.push(out.join(''));out.length=0}else if(c==='\n'){rows.push(out.join('').replace(/\r$/,''));out.length=0;if(rows.length)result.push(rows.splice(0))}else out.push(c)}if(quoted)throw Error('Unclosed CSV quote');if(out.length||rows.length){rows.push(out.join(''));result.push(rows)}return result;}
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw Error('CSV too large (max 2 MB)');const rows=parseCSV(await file.text());if(!rows.length||rows[0].join(',')!=='date,type,description,category,amount_gbp')throw Error('Use CSV exported by Vault (date,type,description,category,amount_gbp)');let imported=[];for(const [i,r] of rows.slice(1).entries()){if(r.length!==5)throw Error('Invalid column count at row '+(i+2));const [date,type,description,cat,amountStr]=r,amount=pennies(amountStr);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00').toString()==='Invalid Date'||!['income','expense'].includes(type)||!description.trim()||description.length>100||!amount)throw Error('Invalid transaction at row '+(i+2));let c=db.categories.find(x=>x.name===cat&&x.type===type);if(!c){c={id:uid(),name:cat.slice(0,30)||'Imported',type,icon:'✦',color:'#849a95'};db.categories.push(c)}imported.push({id:uid(),date,type,description,categoryId:c.id,amount,created:new Date().toISOString(),demo:false})}if(!confirm('Import '+imported.length+' transactions? This adds records and may duplicate existing transactions.'))return;db.transactions.push(...imported);save();render();toast('Imported '+imported.length+' transactions')}catch(err){toast(err.message||'Import failed')}finally{e.target.value=''}};
$('load-demo').onclick=()=>{if(db.demo){toast('Demo data is already loaded');return}if(!confirm('Add example transactions and a savings goal?'))return;const d=new Date();const add=(offset,type,description,cat,amount)=>{const x=new Date(d);x.setDate(x.getDate()-offset);db.transactions.push({id:uid(),type,description,categoryId:db.categories.find(c=>c.name===cat).id,amount,created:new Date().toISOString(),date:x.toLocaleDateString('en-CA'),demo:true})};add(2,'income','Part-time wages','Salary',42000);add(1,'expense','Petrol','Transport',3500);add(3,'expense','Groceries','Food',2400);add(5,'expense','Games','Entertainment',1700);add(9,'income','Side project','Other income',8500);db.goals.push({id:uid(),name:'Holiday fund',target:100000,saved:15000,deadline:'',demo:true});db.demo=true;save();render();toast('Demo data loaded')};
$('clear-demo').onclick=()=>{if(!db.demo){toast('No demo data to clear');return}if(!confirm('Remove demo records?'))return;db.transactions=db.transactions.filter(x=>!x.demo);db.goals=db.goals.filter(x=>!x.demo);db.recurring=db.recurring.filter(x=>!x.demo);db.demo=false;save();render();toast('Demo data cleared')};
$('reset').onclick=()=>{if(!confirm('Permanently erase all Vault Finance data in this browser?'))return;if(!confirm('Are you absolutely sure? Export a backup first.'))return;db=fresh();save();applyTheme();render();toast('All data erased')};
applyRecurring();render();
})();